// WebVTT writer for the captions / transcript file that ships next to each mp3.

function stamp(sec) {
  const ms = Math.round(sec * 1000);
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  const f = ms % 1000;
  const p = (n, w = 2) => String(n).padStart(w, '0');
  return `${p(h)}:${p(m)}:${p(s)}.${p(f, 3)}`;
}

const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** @param {{start:number,end:number,text:string}[]} cues */
export function toVtt(cues, { title } = {}) {
  const lines = ['WEBVTT', ''];
  if (title) lines.push(`NOTE ${title.replace(/\n/g, ' ')}`, 'NOTE Generated by scripts/audio/build.mjs; do not edit by hand.', '');
  cues.forEach((c, i) => {
    lines.push(String(i + 1), `${stamp(c.start)} --> ${stamp(c.end)}`, esc(c.text), '');
  });
  return lines.join('\n');
}

export { stamp };
